package com.order.www.orderInterface.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("pool_batch", "id", Batch.class);
		arp.addMapping("pool_batch_line", "id", BatchLine.class);
		arp.addMapping("pool_task", "id", OrderTask.class);
		arp.addMapping("pool_task_line", "id", TaskLine.class);
		arp.addMapping("pool_json", "id", OrderJson.class);
		arp.addMapping("pool_task_line_money", "id", TaskLineMoney.class);
		arp.addMapping("pool_givemoney", "id", Givemoney.class);
		arp.addMapping("pool_givemoney_order", "id", GivemoneyOrder.class);
	}
}

