package com.order.www.orderInterface.entity;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderJson<M extends BaseOrderJson<M>> extends Model<M> implements IBean {

	/**
	 * 订单集成ID，UUID
	 */
	public void setId(String id) {
		set("id", id);
	}

	/**
	 * 订单集成ID，UUID
	 */
	public String getId() {
		return getStr("id");
	}


	/**
	 * 状态最后改变时间
	 */
	public void setCreateDate(java.util.Date statusChangeDatetime) {
		set("create_date", statusChangeDatetime);
	}

	/**
	 * 状态最后改变时间
	 */
	public java.util.Date getCreateDate() {
		return get("create_date");
	}



	/**
	 */
	public void setContent(String taskType) {
		set("content", taskType);
	}

	/**
	 */
	public String getContent() {
		return getStr("content");
	}


}
