package com.order.www.orderInterface.entity;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBatchLine<M extends BaseBatchLine<M>> extends Model<M> implements IBean {
	/**
	 * 供应商id
	 */
	public void setSupplierID(int id) {
		set("supplierID", id);
	}

	/**
	 * 供应商id
	 */
	public int getSupplierID() {
		return getInt("supplierID");
	}

	/**
	 * 订单集成行ID,UUID
	 */
	public void setSupplierName(java.lang.String id) {
		set("supplierName", id);
	}

	public void setAgentType(java.lang.String id) {
		set("agentType", id);
	}

	public java.lang.String getAgentType() {
		return getStr("agentType");
	}

	public void setSAPSupplierID(java.lang.String id) {
		set("sapSupplierID", id);
	}

	public java.lang.String getSAPSupplierID() {
		return getStr("sapSupplierID");
	}


	/**
	 * 订单集成行ID,UUID
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}


	public void setProductClass(java.lang.String productClass) {
		set("product_class", productClass);
	}
	public void setWhareHouse(java.lang.String productClass) {
		set("whareHouse", productClass);
	}
	public java.lang.String getWhareHouse() {
		return getStr("whareHouse");
	}


	public java.lang.String getProductClass() {
		return getStr("product_class");
	}

	/**
	 * 订单集成行ID，UUID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * 订单集成行ID，UUID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 订单集成id
	 */
	public void setPoolBatchId(java.lang.String poolBatchId) {
		set("POOL_BATCH_ID", poolBatchId);
	}
	
	/**
	 * 订单集成id
	 */
	public java.lang.String getPoolBatchId() {
		return getStr("POOL_BATCH_ID");
	}

	/**
	 * ERP物料编码，订单生产时为空，下单至ERP时回填
	 */
	public void setProductId(java.lang.String productId) {
		set("PRODUCT_ID", productId);
	}
	
	/**
	 * ERP物料编码，订单生产时为空，下单至ERP时回填
	 */
	public java.lang.String getProductId() {
		return getStr("PRODUCT_ID");
	}

	/**
	 * 物料名称
	 */
	public void setNAME(java.lang.String NAME) {
		set("NAME", NAME);
	}
	
	/**
	 * 物料名称
	 */
	public java.lang.String getNAME() {
		return getStr("NAME");
	}

	/**
	 * 数量
	 */
	public void setAMOUNT(java.lang.Integer AMOUNT) {
		set("AMOUNT", AMOUNT);
	}
	
	/**
	 * 数量
	 */
	public java.lang.Integer getAMOUNT() {
		return getInt("AMOUNT");
	}

	/**
	 * 总价格
	 */
	public void setSumPrice(java.math.BigDecimal sumPrice) {
		set("SUM_PRICE", sumPrice);
	}
	
	/**
	 * 总价格
	 */
	public java.math.BigDecimal getSumPrice() {
		return get("SUM_PRICE");
	}

}
