package com.order.www.orderInterface.entity;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGivemoneyOrder<M extends BaseGivemoneyOrder<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return getStr("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	/**
	 * 创建者
	 */
	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	/**
	 * 创建者
	 */
	public String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 更新者
	 */
	public void setUpdateBy(String updateBy) {
		set("update_by", updateBy);
	}

	/**
	 * 更新者
	 */
	public String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	/**
	 * 备注信息
	 */
	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	/**
	 * 备注信息
	 */
	public String getRemarks() {
		return getStr("remarks");
	}

	/**
	 * 删除标记
	 */
	public void setDelFlag(String delFlag) {
		set("del_flag", delFlag);
	}

	/**
	 * 删除标记
	 */
	public String getDelFlag() {
		return getStr("del_flag");
	}

	/**
	 * 订单id
	 */
	public void setOrderID(String orderID) {
		set("orderID", orderID);
	}

	/**
	 * 订单id
	 */
	public String getOrderID() {
		return getStr("orderID");
	}

	/**
	 * 订单日期
	 */
	public void setOrderDate(java.util.Date orderDate) {
		set("orderDate", orderDate);
	}

	/**
	 * 订单日期
	 */
	public java.util.Date getOrderDate() {
		return get("orderDate");
	}

	/**
	 * 金额
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	/**
	 * 金额
	 */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	/**
	 * 商品名称
	 */
	public void setProductName(String productName) {
		set("productName", productName);
	}

	/**
	 * 商品名称
	 */
	public String getProductName() {
		return getStr("productName");
	}

	/**
	 * 数量
	 */
	public void setProductNumber(Integer productNumber) {
		set("productNumber", productNumber);
	}

	/**
	 * 数量
	 */
	public Integer getProductNumber() {
		return getInt("productNumber");
	}

	/**
	 * 物料id
	 */
	public void setItemCode(String itemCode) {
		set("itemCode", itemCode);
	}

	/**
	 * 物料id
	 */
	public String getItemCode() {
		return getStr("itemCode");
	}

	/**
	 * 打款信息id
	 */
	public void setMoneyId(String moneyId) {
		set("money_id", moneyId);
	}

	/**
	 * 打款信息id
	 */
	public String getMoneyId() {
		return getStr("money_id");
	}

}
