package com.order.www.orderInterface.entity;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGivemoney<M extends BaseGivemoney<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return getStr("id");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	/**
	 * 创建者
	 */
	public void setCreateBy(String createBy) {
		set("create_by", createBy);
	}

	/**
	 * 创建者
	 */
	public String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 更新者
	 */
	public void setUpdateBy(String updateBy) {
		set("update_by", updateBy);
	}

	/**
	 * 更新者
	 */
	public String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	/**
	 * 备注信息
	 */
	public void setRemarks(String remarks) {
		set("remarks", remarks);
	}

	/**
	 * 备注信息
	 */
	public String getRemarks() {
		return getStr("remarks");
	}

	/**
	 * 删除标记
	 */
	public void setDelFlag(String delFlag) {
		set("del_flag", delFlag);
	}

	/**
	 * 删除标记
	 */
	public String getDelFlag() {
		return getStr("del_flag");
	}

	/**
	 * 银行账号
	 */
	public void setAccountNumber(String accountNumber) {
		set("accountNumber", accountNumber);
	}

	/**
	 * 银行账号
	 */
	public String getAccountNumber() {
		return getStr("accountNumber");
	}

	/**
	 * 账户名
	 */
	public void setAccountName(String accountName) {
		set("accountName", accountName);
	}

	/**
	 * 账户名
	 */
	public String getAccountName() {
		return getStr("accountName");
	}

	/**
	 * 打款金额
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	/**
	 * 打款金额
	 */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	/**
	 * 银行名称
	 */
	public void setBankName(String bankName) {
		set("bankName", bankName);
	}

	/**
	 * 银行名称
	 */
	public String getBankName() {
		return getStr("bankName");
	}

	/**
	 * 分账用户类型
	 */
	public void setUserType(Integer userType) {
		set("userType", userType);
	}

	/**
	 * 分账用户类型
	 */
	public Integer getUserType() {
		return getInt("userType");
	}

	/**
	 * 分账用户ID
	 */
	public void setUserID(Integer userID) {
		set("userID", userID);
	}

	/**
	 * 分账用户ID
	 */
	public Integer getUserID() {
		return getInt("userID");
	}

	/**
	 * 分账用户类型名称
	 */
	public void setTypeName(String typeName) {
		set("typeName", typeName);
	}

	/**
	 * 分账用户类型名称
	 */
	public String getTypeName() {
		return getStr("typeName");
	}
	/**
	 * 分账用户ID
	 */
	public void setTransferType(Integer userID) {
		set("transferType", userID);
	}

	/**
	 * 分账用户ID
	 */
	public Integer getTransferType() {
		return getInt("transferType");
	}

	/**
	 * 分账用户类型名称
	 */
	public void setYeepayID(String typeName) {
		set("yeepayID", typeName);
	}

	/**
	 * 分账用户类型名称
	 */
	public String getYeepayID() {
		return getStr("yeepayID");
	}
}
