package com.order.www.orderInterface.entity;

import com.order.www.orderInterface.entity.BaseBatchLine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BatchLine extends BaseBatchLine<BatchLine> {
	
}
