package com.order.www.orderInterface.entity;

import com.order.www.orderInterface.entity.BaseBatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Batch extends BaseBatch<Batch> {
	
}
