package com.order.www.orderInterface.entity;

import com.order.www.orderInterface.entity.BaseTaskLine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaskLine extends BaseTaskLine<TaskLine> {
	
}
